export const ERROR_TYPES = {
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
  EMAIL_DO_NOT_MATCH_REGEX: 'EMAIL_DO_NOT_MATCH_REGEX',
  USERNAME_DO_NOT_MATCH_REGEX: 'USERNAME_DO_NOT_MATCH_REGEX',
  PASSWORD_DO_NOT_MATCH_REGEX: 'PASSWORD_DO_NOT_MATCH_REGEX',
  SIGN_UP_FAILED: 'SIGN_UP_FAILED',
};
